p8105_hw2_sz3214
================
Shizhe Zhang
2024-09-30

# Problem 1

## Import and Clean data

``` r
mta = 
  read_csv('data/NYC_Transit_Subway_Entrance_And_Exit_Data.csv', na = c("NA", ".", "")) |> 
  janitor::clean_names() |> 
  select(line:entry, vending, ada) |> 
  mutate(entry=ifelse(entry == "YES", TRUE, FALSE))
```

    ## Rows: 1868 Columns: 32
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (22): Division, Line, Station Name, Route1, Route2, Route3, Route4, Rout...
    ## dbl  (8): Station Latitude, Station Longitude, Route8, Route9, Route10, Rout...
    ## lgl  (2): ADA, Free Crossover
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
head(mta, 10)
```

    ## # A tibble: 10 × 19
    ##    line     station_name station_latitude station_longitude route1 route2 route3
    ##    <chr>    <chr>                   <dbl>             <dbl> <chr>  <chr>  <chr> 
    ##  1 4 Avenue 25th St                  40.7             -74.0 R      <NA>   <NA>  
    ##  2 4 Avenue 25th St                  40.7             -74.0 R      <NA>   <NA>  
    ##  3 4 Avenue 36th St                  40.7             -74.0 N      R      <NA>  
    ##  4 4 Avenue 36th St                  40.7             -74.0 N      R      <NA>  
    ##  5 4 Avenue 36th St                  40.7             -74.0 N      R      <NA>  
    ##  6 4 Avenue 45th St                  40.6             -74.0 R      <NA>   <NA>  
    ##  7 4 Avenue 45th St                  40.6             -74.0 R      <NA>   <NA>  
    ##  8 4 Avenue 45th St                  40.6             -74.0 R      <NA>   <NA>  
    ##  9 4 Avenue 45th St                  40.6             -74.0 R      <NA>   <NA>  
    ## 10 4 Avenue 53rd St                  40.6             -74.0 R      <NA>   <NA>  
    ## # ℹ 12 more variables: route4 <chr>, route5 <chr>, route6 <chr>, route7 <chr>,
    ## #   route8 <dbl>, route9 <dbl>, route10 <dbl>, route11 <dbl>,
    ## #   entrance_type <chr>, entry <lgl>, vending <chr>, ada <lgl>

The dataset contains variables: line, station_name, station_latitude,
station_longitude, route1, route2, route3, route4, route5, route6,
route7, route8, route9, route10, route11, entrance_type, entry, vending,
ada. First, read the cvs file and clean its column names. Second, select
all the variables you want. Third, change the `entry` variable from
character to logical. The dataset has 1868 rows and 19 columns. The
dataset is not tidy enough.

## Answer questions

``` r
distinct(mta, line, station_name) |> 
  nrow()
```

    ## [1] 465

There are 465 distinct stations.

``` r
filter(mta, ada == TRUE) |> 
  distinct(line, station_name) |> 
  nrow()
```

    ## [1] 84

There are 84 ADA compliant.

``` r
filter(mta, entry = TRUE, vending == "NO") |> 
  summarise(proportion = n() / nrow(mta)) 
```

    ## # A tibble: 1 × 1
    ##   proportion
    ##        <dbl>
    ## 1     0.0980

The proportion of station entrances / exits without vending allow
entrance is 9.8%.

``` r
mta_edt = mta |> 
  mutate(across(route1:route11, as.character)) |> 
  pivot_longer(
    cols = route1:route11, names_to = "route_number", values_to = "route") 

mta_edt |> 
  filter(route == "A") |> 
  distinct(line, station_name) |> 
  count()
```

    ## # A tibble: 1 × 1
    ##       n
    ##   <int>
    ## 1    60

``` r
mta_edt |> 
  filter(route == "A", ada == TRUE) |> 
  distinct(line, station_name) |> 
  count()
```

    ## # A tibble: 1 × 1
    ##       n
    ##   <int>
    ## 1    17

80 distinct stations serve the A train. Of the stations that serve the A
train, 17 are ADA compliant.

## Problem 2

``` r
mr_trash =
  read_excel('data/202409 Trash Wheel Collection Data.xlsx', sheet = 1, na = c("NA", ".", "")) |> 
  janitor::clean_names() |> 
  select(dumpster:homes_powered) |> 
  mutate(sports_balls = as.integer(round(sports_balls)),
         trash_type = "Mr. Trash Wheel", 
         year = as.integer(year))
```

    ## New names:
    ## • `` -> `...15`
    ## • `` -> `...16`

``` r
pro_trash =
  read_excel('data/202409 Trash Wheel Collection Data.xlsx', sheet = 2, na = c("NA", ".", "")) |> 
  janitor::clean_names() |> 
  select(dumpster:homes_powered) |> 
  mutate(trash_type = "Professor Trash Wheel", 
         year = as.integer(year))

gwynnda=
  read_excel('data/202409 Trash Wheel Collection Data.xlsx', sheet = 4, na = c("NA", ".", "")) |> 
  janitor::clean_names() |> 
  select(dumpster:homes_powered) |> 
  mutate(trash_type = "Gwynnda Trash Wheel", 
         year = as.integer(year))

trash = 
  bind_rows(mr_trash, pro_trash, gwynnda)  
```

There are 1038 of observations in the trash dataset and variables
including dumpster, month, year, date, weight_tons, volume_cubic_yards,
plastic_bottles, polystyrene, cigarette_butts, glass_bottles,
plastic_bags, wrappers, sports_balls, homes_powered, trash_type.

``` r
pro_trash |> 
  summarise(sum(weight_tons, na.rm = TRUE))
```

    ## # A tibble: 1 × 1
    ##   `sum(weight_tons, na.rm = TRUE)`
    ##                              <dbl>
    ## 1                              488

Total weifht of trash collected by Professor Trash Wheel is 488 tons.

``` r
gwynnda |> 
  filter(year==2022, month=="June") |> 
  summarise(sum(cigarette_butts, na.rm = TRUE))
```

    ## # A tibble: 1 × 1
    ##   `sum(cigarette_butts, na.rm = TRUE)`
    ##                                  <dbl>
    ## 1                                18120

The total number of cigarette butts collected by Gwynnda in June of 2022
is 18120.

# Problem 3

``` r
bakers = 
  read_csv('data/gbb_datasets/bakers.csv', na = c("NA", ".", "")) |> 
  janitor::clean_names() |> 
  separate(baker_name, into = c("first_name", "last_name"), sep = " ") 
```

    ## Rows: 120 Columns: 5
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (3): Baker Name, Baker Occupation, Hometown
    ## dbl (2): Series, Baker Age
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
bakes = 
  read_csv('data/gbb_datasets/bakes.csv', na = c("NA", ".", "")) |> 
  janitor::clean_names() |> 
  rename(first_name=baker)
```

    ## Rows: 548 Columns: 5
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (3): Baker, Signature Bake, Show Stopper
    ## dbl (2): Series, Episode
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
results = 
  read_csv('data/gbb_datasets/results.csv', skip=2, na = c("NA", ".", "")) |> 
  janitor::clean_names() |> 
  rename(first_name=baker)
```

    ## Rows: 1136 Columns: 5
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (2): baker, result
    ## dbl (3): series, episode, technical
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
viewers = 
  read_csv('data/gbb_datasets/viewers.csv', na = c("NA", ".", "")) |>
  janitor::clean_names() |> 
  pivot_longer(
    cols = series_1:series_10,
    names_to = "series",
    values_to = "viewer"
  ) |> 
  mutate(series = str_replace(series, "series_", "")) |> 
  mutate(series = as.integer(series))
```

    ## Rows: 10 Columns: 11
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl (11): Episode, Series 1, Series 2, Series 3, Series 4, Series 5, Series ...
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

check and correct tables

``` r
anti_join(bakers, bakes, by = "first_name")
```

    ## # A tibble: 23 × 6
    ##    first_name last_name       series baker_age baker_occupation         hometown
    ##    <chr>      <chr>            <dbl>     <dbl> <chr>                    <chr>   
    ##  1 Alice      Fevronia            10        28 Geography teacher        Essex   
    ##  2 Amelia     LeBruin             10        24 Fashion designer         Halifax 
    ##  3 Antony     Amourdoux            9        30 Banker                   London  
    ##  4 Briony     Williams             9        33 Full-time parent         Bristol 
    ##  5 Dan        Beasley-Harling      9        36 Full-time parent         London  
    ##  6 Dan        Chambers            10        32 Support worker           Rotherh…
    ##  7 Helena     Garcia              10        40 Online project manager   Leeds   
    ##  8 Henry      Bird                10        20 Student                  Durham  
    ##  9 Imelda     McCarron             9        33 Countryside recreation … County …
    ## 10 Jamie      Finn                10        20 Part-time waiter         Surrey  
    ## # ℹ 13 more rows

``` r
anti_join(bakers, results, by = "first_name")
```

    ## # A tibble: 1 × 6
    ##   first_name last_name series baker_age baker_occupation hometown    
    ##   <chr>      <chr>      <dbl>     <dbl> <chr>            <chr>       
    ## 1 Jo         Wheatley       2        41 Housewife        Ongar, Essex

``` r
anti_join(bakes, results, by = c("series", "episode"))
```

    ## # A tibble: 0 × 5
    ## # ℹ 5 variables: series <dbl>, episode <dbl>, first_name <chr>,
    ## #   signature_bake <chr>, show_stopper <chr>

``` r
bakers|>
  mutate(first_name = ifelse(first_name == "Jo","Joanne", first_name))
```

    ## # A tibble: 120 × 6
    ##    first_name last_name   series baker_age baker_occupation             hometown
    ##    <chr>      <chr>        <dbl>     <dbl> <chr>                        <chr>   
    ##  1 Ali        Imdad            4        25 Charity worker               Saltley…
    ##  2 Alice      Fevronia        10        28 Geography teacher            Essex   
    ##  3 Alvin      Magallanes       6        37 Nurse                        Brackne…
    ##  4 Amelia     LeBruin         10        24 Fashion designer             Halifax 
    ##  5 Andrew     Smyth            7        25 Aerospace engineer           Derby /…
    ##  6 Annetha    Mills            1        30 Midwife                      Essex   
    ##  7 Antony     Amourdoux        9        30 Banker                       London  
    ##  8 Beca       Lyne-Pirkis      4        31 Military Wives' Choir Singer Aldersh…
    ##  9 Ben        Frazer           2        31 Graphic Designer             Northam…
    ## 10 Benjamina  Ebuehi           7        23 Teaching assistant           South L…
    ## # ℹ 110 more rows

merge data

``` r
gbb = 
  left_join(bakes, bakers, by = c("first_name","series")) |> 
  left_join(results, by = c("first_name","series", "episode")) |> 
  left_join(viewers, by = c("series", "episode")) |> 
  relocate(series,episode,first_name,last_name, signature_bake,show_stopper,technical,result,baker_age, baker_occupation, hometown)
```

export

``` r
write_csv(gbb, 'data/gbb_datasets/gbb.csv')
```
